### numpy的简单介绍

numpy在神经网络中会被经常使用，因为python自带的list效率比较低，运算速度很慢，这里只知道简单的numpy操作即可

In [6]:
import numpy as np

# numpy可以将list转成array，相当于将列表转成静态数组
l1=[[1,2],
    [3,4],
    [5,6]]
nl1=np.array(l1)

print(nl1)
print(nl1[2,:])

[[1 2]
 [3 4]
 [5 6]]
[5 6]


In [8]:
# 矩阵点乘(常规意义上的矩阵乘法)
nl2=nl1.T
y=np.dot(nl1,nl2)
y

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [9]:
#花乘（矩阵元素直接逐项相乘）
y1=np.array([[1,2],[3,4]])
y2=np.array([[1,2],[3,4]])

print("y1+y2 :",y1+y2)
print("y1*y2 :",y1*y2)

y1+y2 : [[2 4]
 [6 8]]
y1*y2 : [[ 1  4]
 [ 9 16]]


In [12]:
#求不同维度的平均值
col=np.mean(y1,axis=0)
row=np.mean(y1,axis=1)
row,col

(array([1.5, 3.5]), array([2., 3.]))

In [14]:
#取矩阵值与设置值中的最大值
y3=np.maximum(3,y1)
y4=np.array([[2,3],[5,4]])
y4=np.maximum(y4,y1)
y3,y4

(array([[3, 3],
        [3, 4]]),
 array([[2, 3],
        [5, 4]]))

In [15]:
# 仅取某一个轴的最大值
a=np.max(y1,axis=0)
a

array([3, 4])